{
    "openapi": "3.1.0",
    "info": {
        "title": "Zoho Analytics Bulk API",
        "version": "v2",
        "description": "API for Zoho Analytics Bulk Operations, including data import and export."
    },
    "servers": [
        {
            "url": "https://analyticsapi.zoho.com"
        }
    ],
    "security": [
        {
            "iam-oauth2-schema": [
                "ZohoAnalytics.data.read",
                "ZohoAnalytics.data.create",
                "ZohoAnalytics.data.update",
                "ZohoAnalytics.data.delete",
                "ZohoAnalytics.data.all"
            ]
        }
    ],
    "tags": [
        {
            "name": "Bulk Import - Synchronous",
            "description": "Synchronous operations for importing data."
        },
        {
            "name": "Bulk Import - Asynchronous",
            "description": "Asynchronous operations for importing data in bulk."
        },
        {
            "name": "Bulk Import - Batch",
            "description": "Operations for importing large data files in batches."
        },
        {
            "name": "Bulk Export - Synchronous",
            "description": "Synchronous operations for exporting data."
        },
        {
            "name": "Bulk Export - Asynchronous",
            "description": "Asynchronous operations for exporting data in bulk."
        }
    ],
    "paths": {
        "/restapi/v2/workspaces/{workspace-id}/data": {
            "post": {
                "tags": [
                    "Bulk Import - Synchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.create"
                        ]
                    }
                ],
                "summary": "Import Data into a New Table (Synchronous)",
                "description": "Use the Bulk APIs to create a new table and import data into it synchronously. ",
                "operationId": "importDataNewTable"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/data": {
            "post": {
                "tags": [
                    "Bulk Import - Synchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.create"
                        ]
                    }
                ],
                "summary": "Import Data into an Existing Table (Synchronous)",
                "description": "Use Bulk APIs to import data into an existing specified table synchronously.",
                "operationId": "importDataExistingTable"
            },
            "get": {
                "tags": [
                    "Bulk Export - Synchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.read"
                        ]
                    }
                ],
                "summary": "Export Data from a View (Synchronous)",
                "description": "Use Bulk APIs to export data from the specified view synchronously.\n\nNote: Export Data API is restricted for certain resources (given below). For these cases, use the Asynchronous Export APIs instead:\n\n  - Tables having more than one million rows.\n  - Tables and Views from live connect workspaces.\n  - Dashboard and QueryTable view types.",
                "operationId": "exportDataView"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/data/batch": {
            "post": {
                "tags": [
                    "Bulk Import - Batch"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.create"
                        ]
                    }
                ],
                "summary": "Batch Import Data into New Table",
                "description": "Initiate an import job to create a new table and import data in batches into the created table.\n\n The Batch Import API allows you to upload large amounts of data in batches. A large data file is split into small batches, each batch not exceeding 100 MB, and imported using batch import. Alternatively, you can also use Zoho Analytics SDKs to simplify the batching process.\n\nTo import large amounts of data using Batch Import, follow the steps below:\n\n- Split the[...]",
                "operationId": "batchImportNewTable"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/views/{view-id}/data/batch": {
            "post": {
                "tags": [
                    "Bulk Import - Batch"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.create"
                        ]
                    }
                ],
                "summary": "Batch Import Data into Existing Table",
                "description": "Initiate an import job to import data present in multiple batch files into the specified existing table.\n\n The Batch Import API allows you to upload large amounts of data in batches. A large data file is split into small batches, each batch not exceeding 100 MB, and imported using batch import. Alternatively, you can also use Zoho Analytics SDKs to simplify the batching process.\n\nTo import large amounts of data using Batch Import, follow the steps below:\n\n- [...]",
                "operationId": "batchImportExistingTable"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/data": {
            "get": {
                "tags": [
                    "Bulk Export - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.read"
                        ]
                    }
                ],
                "summary": "Create Export Job using SQL Query (Asynchronous)",
                "description": "Create an export job using an SQL SELECT statement to initiate data export asynchronously.\n\nWorkflow:\n1. Create Export Job:\n  - Call the Create Export Job API.\n  - Receive a unique JOBID to track the export status.\n\n2. Check Export Job Status:\n  - Use the JOBID with the Get Export Job Details API.\n  - Poll every few seconds to get the current JOBCODE.\n\n   JOBCODEs and Meaning:\n   - 1001: JOB NOT INITIATED\n     → Export job acknowledged but not started[...]",
                "operationId": "createExportJobSQLQuery"
            },
            "post": {
                "tags": [
                    "Bulk Import - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.create"
                        ]
                    }
                ],
                "summary": "Create Import Job for a New Table (Asynchronous)",
                "description": "Create an import job to import data into a new table asynchronously. Max allowed file size is 100 MB.\n\nWorkflow of Asynchronous Import API:\n\n1. Create Import Job:\n   - Initiate the import by calling the Create Import Job API.\n   - A unique JOBID will be returned in the response, which serves as the reference for tracking the import job.\n\n2. Check Job Status:\n   - Use the Get Import Job Details API to monitor the status of the import job.\n   - The JOBID m[...]",
                "operationId": "createImportJobNewTable"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/views/{view-id}/data": {
            "get": {
                "tags": [
                    "Bulk Export - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.read"
                        ]
                    }
                ],
                "summary": "Create Export Job using View ID (Asynchronous)",
                "description": "Create an export job to initiate data export for the mentioned view asynchronously. \n\nWorkflow:\n1. Create Export Job:\n  - Call the Create Export Job API.\n  - Receive a unique JOBID to track the export status.\n\n2. Check Export Job Status:\n  - Use the JOBID with the Get Export Job Details API.\n  - Poll every few seconds to get the current JOBCODE.\n\n   JOBCODEs and Meaning:\n   - 1001: JOB NOT INITIATED\n     → Export job acknowledged but not started. Retr[...]",
                "operationId": "createExportJobViewId"
            },
            "post": {
                "tags": [
                    "Bulk Import - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.create"
                        ]
                    }
                ],
                "summary": "Create Import Job for an Existing Table (Asynchronous)",
                "description": "Create an import job to import data into a specified existing table asynchronously. Max allowed file size is 100 MB. \n\nWorkflow of Asynchronous Import API:\n\n1. Create Import Job:\n   - Initiate the import by calling the Create Import Job API.\n   - A unique JOBID will be returned in the response, which serves as the reference for tracking the import job.\n\n2. Check Job Status:\n   - Use the Get Import Job Details API to monitor the status of the import job.\n[...]",
                "operationId": "createImportJobExistingTable"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/importjobs/{job-id}": {
            "get": {
                "tags": [
                    "Bulk Import - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.read"
                        ]
                    }
                ],
                "summary": "Get Import Job Details",
                "description": "Returns details of the specified asynchronous import job.",
                "operationId": "getImportJobDetails"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/exportjobs/{job-id}": {
            "get": {
                "tags": [
                    "Bulk Export - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.read"
                        ]
                    }
                ],
                "summary": "Get Export Job Details",
                "description": "Returns details of the specified asynchronous export job.",
                "operationId": "getExportJobDetails"
            }
        },
        "/restapi/v2/bulk/workspaces/{workspace-id}/exportjobs/{job-id}/data": {
            "get": {
                "tags": [
                    "Bulk Export - Asynchronous"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.data.read"
                        ]
                    }
                ],
                "summary": "Download Exported Data",
                "description": "Download data for the bulk export job.",
                "operationId": "downloadExportedData"
            }
        }
    },
    "components": {
        "securitySchemes": {
      "iam-oauth2-schema": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.zoho.com/oauth/v2/auth",
            "tokenUrl": "https://accounts.zoho.com/oauth/v2/token",
            "refreshUrl": "https://accounts.zoho.com/oauth/v2/token",
            "scopes": {
              "ZohoAnalytics.data.read": "Read data from Zoho Analytics.",
              "ZohoAnalytics.data.delete": "Delete data from Zoho Analytics.",
              "ZohoAnalytics.data.update": "Update data in Zoho Analytics.",
              "ZohoAnalytics.data.create": "Create data in Zoho Analytics.",
              "ZohoAnalytics.data.all": "Full access to data in Zoho Analytics.",
              "ZohoAnalytics.fullaccess.all": "Full access to all Zoho Analytics features."
            }
          }
        }
      }
    }
    }
}
