{
    "openapi": "3.1.0",
    "info": {
        "title": "Zoho Analytics API",
        "version": "v2",
        "description": "API for managing data in Zoho Analytics workspaces and views."
    },
    "servers": [
        {
            "url": "https://analyticsapi.zoho.com",
            "description": "US Server"
        },
        {
            "url": "https://analyticsapi.zoho.eu",
            "description": "EU Server"
        },
        {
            "url": "https://analyticsapi.zoho.in",
            "description": "IN Server"
        },
        {
            "url": "https://analyticsapi.zoho.com.au",
            "description": "AU Server"
        },
        {
            "url": "https://analyticsapi.zoho.com.cn",
            "description": "CN Server"
        },
        {
            "url": "https://analyticsapi.zoho.jp",
            "description": "JP Server"
        },
        {
            "url": "https://analyticsapi.zoho.sa",
            "description": "SA Server"
        },
        {
            "url": "https://analyticsapi.zohocloud.ca",
            "description": "CA Server"
        }
    ],
    "tags": [
        {
            "name": "Embed APIs",
            "description": "Embed APIs let you dynamically integrate Zoho Analytics reports and dashboards into your websites and applications."
        }
    ],
    "paths": {
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/publish": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get View URL",
                "description": "Returns the URL to access the specified view.",
                "operationId": "getViewUrl"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/publish/embed": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get Embed URL",
                "description": "Returns embed URL to access the specified view.",
                "operationId": "getEmbedUrl"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/publish/privatelink": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get Private URL",
                "description": "Returns private URL to access the specified view.",
                "operationId": "getPrivateUrl"
            },
            "post": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.update"
                        ]
                    }
                ],
                "summary": "Create Private URL",
                "description": "Create a private URL for the specified view.",
                "operationId": "createPrivateUrl"
            },
            "delete": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.delete"
                        ]
                    }
                ],
                "summary": "Remove Private Access",
                "description": "Remove private link access for the specified view.",
                "operationId": "removePrivateAccess"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/publish/public": {
            "post": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.create"
                        ]
                    }
                ],
                "summary": "Make Views Public",
                "description": "Make the specified view publicly accessible.",
                "operationId": "makeViewsPublic"
            },
            "delete": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.delete"
                        ]
                    }
                ],
                "summary": "Remove Public Permission",
                "operationId": "removePublicPermission"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/publish/config": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get Publish Configurations",
                "operationId": "getPublishConfigurations"
            },
            "put": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.update"
                        ]
                    }
                ],
                "summary": "Update Publish Configurations",
                "operationId": "updatePublishConfigurations"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/slides": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get Slideshows",
                "operationId": "getSlideshows"
            },
            "post": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.create"
                        ]
                    }
                ],
                "summary": "Create Slideshow",
                "description": "Create a slideshow in the specified workspace.",
                "operationId": "createSlideshow"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/slides/{slide-id}": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get Slideshow Details",
                "operationId": "getSlideshowDetails"
            },
            "put": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.update"
                        ]
                    }
                ],
                "summary": "Update Slideshow",
                "description": "Update details of the specified slideshow.",
                "operationId": "updateSlideshow"
            },
            "delete": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.delete"
                        ]
                    }
                ],
                "summary": "Delete Slideshow",
                "description": "Delete a specified slideshow in the workspace.",
                "operationId": "deleteSlideshow"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/slides/{slide-id}/publish": {
            "get": {
                "tags": [
                    "Embed APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.embed.read"
                        ]
                    }
                ],
                "summary": "Get Slideshow URL",
                "operationId": "getSlideshowUrl"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "iam-oauth2-schema": {
                "$ref": "https://raw.githubusercontent.com/zoho/analytics-oas/refs/heads/main/v2.0/zoho-analytics-api-common.json#/components/securitySchemes/iam-oauth2-schema"
            }
        }
    }
}