{
    "openapi": "3.1.0",
    "info": {
        "title": "Zoho Analytics API",
        "version": "v2",
        "description": "API for managing data in Zoho Analytics workspaces and views."
    },
    "servers": [
        {
            "url": "https://analyticsapi.zoho.com"
        }
    ],
    "tags": [
        {
            "name": "Metadata APIs",
            "description": "Metadata APIs are used to fetch information about the reporting Workspaces, tables, reports, and dashboards created in Zoho Analytics."
        }
    ],
    "paths": {
        "/restapi/v2/orgs": {
            "get": {
                "operationId": "getOrganizations",
                "summary": "Get organizations",
                "description": "Retrieve a list of organizations accessible by the authenticated user.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces": {
            "get": {
                "operationId": "getAllWorkspaces",
                "summary": "Get all workspaces",
                "description": "Retrieve a list of all workspaces accessible by the authenticated user.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/owned": {
            "get": {
                "operationId": "getOwnedWorkspaces",
                "summary": "Get owned workspaces",
                "description": "Retrieve a list of workspaces owned by the authenticated user.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/shared": {
            "get": {
                "operationId": "getSharedWorkspaces",
                "summary": "Get shared workspaces",
                "description": "Retrieve a list of workspaces shared with the authenticated user.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Views",
                "operationId": "getViews"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/folders": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Folders",
                "operationId": "getFolders"
            }
        },
        "/restapi/v2/recentviews": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Recent Views",
                "description": "Returns list of recently accessed views.",
                "operationId": "getRecentViews"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/trash": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Trash Views",
                "description": "Returns list of all views available in trash for the specified workspace.",
                "operationId": "getTrashViews"
            }
        },
        "/restapi/v2/dashboards": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Dashboards",
                "description": "Returns list of all accessible dashboards.",
                "operationId": "getDashboards"
            }
        },
        "/restapi/v2/dashboards/owned": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Owned Dashboards",
                "operationId": "getOwnedDashboards"
            }
        },
        "/restapi/v2/dashboards/shared": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Shared Dashboards",
                "operationId": "getSharedDashboards"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/secretkey": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Workspace Secret Key",
                "operationId": "getWorkspaceSecretKey"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Workspace Details",
                "operationId": "getWorkspaceDetails"
            }
        },
        "/restapi/v2/views/{view-id}": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get View Details",
                "operationId": "getViewDetails"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/dependents": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get View Dependents",
                "operationId": "getViewDependents"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns/{column-id}/dependents": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Column Dependents",
                "operationId": "getColumnDependents"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/favorite": {
            "post": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Add Favorite Workspace",
                "operationId": "addFavoriteWorkspace"
            },
            "delete": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Remove Favorite Workspace",
                "operationId": "removeFavoriteWorkspace"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/default": {
            "post": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Add Default Workspace",
                "operationId": "addDefaultWorkspace"
            },
            "delete": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Remove Default Workspace",
                "operationId": "removeDefaultWorkspace"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/favorite": {
            "post": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Add Favorite View",
                "operationId": "addFavoriteView"
            },
            "delete": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Remove Favorite View",
                "operationId": "removeFavoriteView"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/template/data": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Export as Template",
                "operationId": "exportAsTemplate"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/customformulas": {
            "get": {
                "summary": "Get Custom Formula List",
                "description": "Returns list of all formula columns for the specified table.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "operationId": "getCustomFormulaList"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/aggregateformulas": {
            "get": {
                "summary": "Get Aggregate Formula List",
                "description": "Returns list of all aggregate formulas for the specified table.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "operationId": "getAggregateFormulaList"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/aggregateformulas": {
            "get": {
                "summary": "Get Aggregate Formulas In Workspace",
                "description": "Returns list of all aggregate formulas for the specified workspace.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "operationId": "getAggregateFormulasInWorkspace"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/aggregateformulas/{formula-id}/dependents": {
            "get": {
                "summary": "Get Aggregate Formula Dependents",
                "description": "Returns list of all dependent views and formulas for the specified aggregate formula.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "operationId": "getAggregateFormulaDependents"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/aggregateformulas/{formula-id}/value": {
            "get": {
                "summary": "Get Aggregate Formula Value",
                "description": "Returns the value of the aggregate formula.",
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "operationId": "getAggregateFormulaValue"
            }
        },
        "/restapi/v2/metadetails": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Meta Details",
                "description": "Returns details of the specified workspace or view.",
                "operationId": "getMetaDetails"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/emailschedules": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Email Schedules",
                "description": "Returns list of email schedules available in the specified workspace.",
                "operationId": "getEmailSchedules"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/datasources": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Datasources",
                "description": "Fetches datasources for the specified view.",
                "operationId": "getDatasources"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/importdetails": {
            "get": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.read"
                        ]
                    }
                ],
                "summary": "Get Last Import Details",
                "description": "Returns details of the last data import for the specified view.",
                "operationId": "getLastImportDetails"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/datasource/{datasource-id}/sync": {
            "post": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.create"
                        ]
                    }
                ],
                "summary": "Sync Data",
                "description": "Triggers a manual data sync for the specified view's datasource.",
                "operationId": "syncDatasource"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/sync": {
            "post": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.create"
                        ]
                    }
                ],
                "summary": "Refetch Data",
                "description": "Refetches data from the source for the specified view.",
                "operationId": "refetchDatasource"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/datasource/{datasource-id}": {
            "put": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Update Datasource Connection",
                "description": "Updates the datasource connection details for the specified view.",
                "operationId": "updateDatasourceConnection"
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/wlaccess": {
            "post": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Enable Domain Workspace",
                "description": "Enable workspace access for a specified white label domain.",
                "operationId": "enableDomainWorkspace"
            },
            "delete": {
                "tags": [
                    "Metadata APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.metadata.update"
                        ]
                    }
                ],
                "summary": "Disable Domain Workspace",
                "description": "Disable workspace access for the specified white label domain.",
                "operationId": "disableDomainWorkspace"
            }
        }
    },
    "components": {
        "securitySchemes": {
      "iam-oauth2-schema": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.zoho.com/oauth/v2/auth",
            "tokenUrl": "https://accounts.zoho.com/oauth/v2/token",
            "refreshUrl": "https://accounts.zoho.com/oauth/v2/token",
            "scopes": {
              "ZohoAnalytics.metadata.read": "Read metadata resource from Zoho Analytics.",
              "ZohoAnalytics.metadata.delete": "Delete metadata resource from Zoho Analytics.",
              "ZohoAnalytics.metadata.update": "Update metadata resource in Zoho Analytics.",
              "ZohoAnalytics.metadata.create": "Create metadata resource in Zoho Analytics.",
              "ZohoAnalytics.metadata.all": "Full access to metadata in Zoho Analytics.",
              "ZohoAnalytics.fullaccess.all": "Full access to all Zoho Analytics features."
            }
          }
        }
      }
    }
    }
}
