{
    "openapi": "3.1.0",
    "info": {
        "title": "Zoho Analytics API",
        "version": "v2",
        "description": "API for managing data in Zoho Analytics workspaces and views."
    },
    "servers": [
        {
            "url": "https://analyticsapi.zoho.com"
        }
    ],
    "tags": [
        {
            "name": "Modeling APIs",
            "description": "Modeling APIs manage workspaces, views, columns, and folders, and support copying across or within Zoho Analytics accounts."
        }
    ],
    "paths": {
        "/restapi/v2/workspaces": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Create Workspace",
                "description": "Create a blank workspace in the specified organization.",
                "operationId": "createWorkspace",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Copy Workspace",
                "description": "Copy the specified workspace to another org or within the same org.",
                "operationId": "copyWorkspace",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Rename Workspace",
                "description": "Renames the specified workspace.",
                "operationId": "renameWorkspace",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Delete Workspace",
                "description": "Deletes the specified workspace.",
                "operationId": "deleteWorkspace",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/tables": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Create Table",
                "description": "Create a table in the specified workspace.",
                "operationId": "createTable",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/querytables": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Create Query Table",
                "description": "This API allows you to create a query table using a SQL SELECT query.",
                "operationId": "createQueryTable",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/querytables/{table-id}": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Edit Query Table",
                "description": "This API allows you to update an existing query table using a SQL SELECT query.",
                "operationId": "editQueryTable",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/reports": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Create Report",
                "description": "This API allows you to create a report (chart/table/pivot) in a workspace.",
                "operationId": "createReport",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/reports/{report-id}": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Update Report",
                "description": "This API allows you to update the metadata or design of an existing report.",
                "operationId": "updateReport",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/saveas": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Save As View",
                "description": "This API creates a new view by duplicating an existing one.",
                "operationId": "saveAsView",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/movetofolder": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Move Views To Folder",
                "description": "Moves multiple views into a specified folder.",
                "operationId": "moveViewsToFolder",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Rename View",
                "description": "Renames an existing view.",
                "operationId": "renameView",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Delete View",
                "description": "Moves the view to trash.",
                "operationId": "deleteView",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/trash/{view-id}": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Restore Trash View",
                "description": "Restores a view from trash.",
                "operationId": "restoreTrashView",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Delete Trash View",
                "description": "Permanently deletes a view from trash.",
                "operationId": "deleteTrashView",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/folders": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Create Folder",
                "description": "Create a folder under a specified workspace to organize views.",
                "operationId": "createFolder",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/folders/{folder-id}": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Rename Folder",
                "description": "Rename an existing folder in the workspace.",
                "operationId": "renameFolder",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Delete Folder",
                "description": "Delete a folder from the workspace. Optionally delete views within.",
                "operationId": "deleteFolder",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/folders/{folder-id}/default": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Make Default Folder",
                "description": "Set the specified folder as the default folder for a given view type.",
                "operationId": "makeDefaultFolder",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/folders/{folder-id}/move": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Change Folder Hierarchy",
                "description": "Update the hierarchy of a folder (parent or child) and set its parent if needed.",
                "operationId": "changeFolderHierarchy",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/folders/{folder-id}/reorder": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Change Folder Position",
                "description": "Reorder a folder by moving it relative to another folder.",
                "operationId": "changeFolderPosition",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Add Column",
                "description": "This API allows you to add a new column to the specified view.",
                "operationId": "addColumn",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns/{column-id}": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Rename Column",
                "description": "This API allows you to rename a column.",
                "operationId": "renameColumn",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Delete Column",
                "description": "This API deletes the specified column from a view.",
                "operationId": "deleteColumn",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns/{column-id}/lookup": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Add Lookup",
                "description": "This API adds a lookup relationship to a column.",
                "operationId": "addLookup",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Remove Lookup",
                "description": "This API removes the lookup relationship from a column.",
                "operationId": "removeLookup",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns/hide": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Hide Columns",
                "description": "This API hides the specified columns in a view.",
                "operationId": "hideColumns",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns/show": {
            "put": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Show Columns",
                "description": "This API shows the specified hidden columns in a view.",
                "operationId": "showColumns",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{source-workspace-id}/views/copy": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Copy Views",
                "description": "Copy the specified views from one workspace to another workspace.",
                "operationId": "copyViews",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/formulas/copy": {
            "post": {
                "tags": [
                    "Modeling APIs"
                ],
                "summary": "Copy Formulas",
                "description": "Copy the specified formulas from one table to another across workspaces.",
                "operationId": "copyFormulas",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/similarviews": {
            "post": {
                "operationId": "createSimilarViews",
                "summary": "Create Similar Views",
                "description": "Create reports for the specified table based on the reference table.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/autoanalyse": {
            "post": {
                "operationId": "autoAnalyseView",
                "summary": "Auto Analyse View",
                "description": "Auto generate reports for the specified table.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/views/{view-id}/columns/{column-id}/autoanalyse": {
            "post": {
                "operationId": "autoAnalyseColumn",
                "summary": "Auto Analyse Column",
                "description": "Auto generate reports for the specified column.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/variables": {
            "get": {
                "operationId": "getVariables",
                "summary": "Get all variables in a workspace",
                "description": "Retrieve a list of all variables created in the specified workspace.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.read"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            },
            "post": {
                "operationId": "createVariable",
                "summary": "Create a variable",
                "description": "Create a new variable in the specified workspace using a CONFIG JSON.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/variables/{variable-id}": {
            "get": {
                "operationId": "getVariableDetails",
                "summary": "Get details of a specific variable",
                "description": "Fetch metadata and configuration of a variable using its ID in a workspace.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.read"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            },
            "put": {
                "operationId": "updateVariable",
                "summary": "Update a variable",
                "description": "Update an existing variable in the specified workspace using the CONFIG JSON.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            },
            "delete": {
                "operationId": "deleteVariable",
                "summary": "Delete a variable",
                "description": "Delete the specified variable from the workspace.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"  
                            ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/customformulas": {
            "post": {
                "operationId": "addFormulaColumn",
                "summary": "Add Formula Column",
                "description": "Add a new formula column to the specified view.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/customformulas/{formula-id}": {
            "put": {
                "operationId": "editFormulaColumn",
                "summary": "Edit Formula Column",
                "description": "Update an existing formula column in the view.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            },
            "delete": {
                "operationId": "deleteFormulaColumn",
                "summary": "Delete Formula Column",
                "description": "Delete a formula column from the specified view.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                            ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/aggregateformulas": {
            "post": {
                "operationId": "addAggregateFormula",
                "summary": "Add Aggregate Formula",
                "description": "Add an aggregate formula column to the specified view.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/aggregateformulas/{formula-id}": {
            "put": {
                "operationId": "editAggregateFormula",
                "summary": "Edit Aggregate Formula",
                "description": "Update an existing aggregate formula column in the view.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            },
            "delete": {
                "operationId": "deleteAggregateFormula",
                "summary": "Delete Aggregate Formula",
                "description": "Delete an aggregate formula column from the specified view.",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ],
                "tags": [
                    "Modeling APIs"
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/emailschedules": {
            "post": {
                "operationId": "createEmailSchedule",
                "summary": "Create Email Schedule",
                "description": "Create an email schedule for a view.",
                "tags": [
                    "Modeling APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/emailschedules/{schedule-id}": {
            "put": {
                "operationId": "updateEmailSchedule",
                "summary": "Update Email Schedule",
                "description": "Update an existing email schedule.",
                "tags": [
                    "Modeling APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            },
            "delete": {
                "operationId": "deleteEmailSchedule",
                "summary": "Delete Email Schedule",
                "description": "Delete the specified email schedule.",
                "tags": [
                    "Modeling APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.delete"
                        ]
                    }
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/emailschedules/{schedule-id}/trigger": {
            "post": {
                "operationId": "triggerEmailSchedule",
                "summary": "Trigger Email Schedule",
                "description": "Manually trigger the specified email schedule.",
                "tags": [
                    "Modeling APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.create"
                        ]
                    }
                ]
            }
        },
        "/workspaces/{workspace-id}/views/{view-id}/emailschedules/{schedule-id}/status": {
            "put": {
                "operationId": "changeEmailScheduleStatus",
                "summary": "Change Email Schedule Status",
                "description": "Enable or disable the specified email schedule.",
                "tags": [
                    "Modeling APIs"
                ],
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.modeling.update"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
      "iam-oauth2-schema": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.zoho.com/oauth/v2/auth",
            "tokenUrl": "https://accounts.zoho.com/oauth/v2/token",
            "refreshUrl": "https://accounts.zoho.com/oauth/v2/token",
            "scopes": {
              "ZohoAnalytics.modeling.delete": "Delete modeling objects in Zoho Analytics.",
              "ZohoAnalytics.modeling.update": "Update modeling objects in Zoho Analytics.",
              "ZohoAnalytics.modeling.create": "Create modeling objects in Zoho Analytics.",
              "ZohoAnalytics.modeling.all": "Full access to modeling objects in Zoho Analytics.",
              "ZohoAnalytics.fullaccess.all": "Full access to all Zoho Analytics features."
            }
          }
        }
      }
    }
    }
}
