{
    "openapi": "3.1.0",
    "info": {
        "title": "Zoho Analytics API",
        "version": "v2",
        "description": "API for managing data in Zoho Analytics workspaces and views."
    },
    "servers": [
        {
            "url": "https://analyticsapi.zoho.com"
        }
    ],
    "tags": [
        {
            "name": "User Management APIs",
            "description": "Manage User APIs allow you to add, remove, activate, or deactivate users in your Zoho Analytics organization programmatically."
        }
    ],
    "paths": {
        "/restapi/v2/users": {
            "get": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Get Users",
                "description": "Returns list of users for the specified organization.",
                "operationId": "getUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Add Users",
                "description": "Add users to the specified organization.",
                "operationId": "addUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.create"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Remove Users",
                "description": "Remove users from the specified organization.",
                "operationId": "removeUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/users/active": {
            "put": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Activate Users",
                "description": "Activate users in the specified organization.",
                "operationId": "activateUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/users/inactive": {
            "put": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Deactivate Users",
                "description": "Deactivate users in the specified organization.",
                "operationId": "deActivateUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/users/role": {
            "put": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Change User Role",
                "description": "Change role for the specified users.",
                "operationId": "changeUserRole",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/subscription": {
            "get": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Get Subscription Details",
                "description": "Returns subscription details of the specified organization.",
                "operationId": "getSubscriptionDetails",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.read"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/resources": {
            "get": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Get Resource Details",
                "description": "Returns resource usage details of the specified organization.",
                "operationId": "getResourceDetails",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.read"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/users": {
            "get": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Get Workspace Users",
                "description": "Returns list of users for the specified workspace.",
                "operationId": "getWorkspaceUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Add Workspace Users",
                "description": "Add users to the specified workspace.",
                "operationId": "addWorkspaceUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.create"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Delete Workspace Users",
                "description": "Delete users from the specified workspace.",
                "operationId": "deleteWorkspaceUsers",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.delete"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/users/status": {
            "put": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Change Workspace Users Status",
                "description": "Update activation status of users in a Zoho Analytics workspace.",
                "operationId": "changeWorkspaceUsersStatus",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.update"
                        ]
                    }
                ]
            }
        },
        "/restapi/v2/workspaces/{workspace-id}/users/role": {
            "put": {
                "tags": [
                    "User Management APIs"
                ],
                "summary": "Change Workspace Users Role",
                "description": "Update role of users in a Zoho Analytics workspace.",
                "operationId": "changeWorkspaceUsersRole",
                "security": [
                    {
                        "iam-oauth2-schema": [
                            "ZohoAnalytics.usermanagement.update"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
      "iam-oauth2-schema": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.zoho.com/oauth/v2/auth",
            "tokenUrl": "https://accounts.zoho.com/oauth/v2/token",
            "refreshUrl": "https://accounts.zoho.com/oauth/v2/token",
            "scopes": {
              "ZohoAnalytics.usermanagement.read": "Read user management data in Zoho Analytics.",
              "ZohoAnalytics.usermanagement.delete": "Delete user management data in Zoho Analytics.",
              "ZohoAnalytics.usermanagement.update": "Update user management data in Zoho Analytics.",
              "ZohoAnalytics.usermanagement.create": "Create user management data in Zoho Analytics.",
              "ZohoAnalytics.usermanagement.all": "Full access to user management in Zoho Analytics.",
              "ZohoAnalytics.fullaccess.all": "Full access to all Zoho Analytics features."
            }
          }
        }
      }
    }
    }
}
